### ISSUE TITLE
SW:Linux wiki page Linux kernel/initrd not compatible

### ISSUE THREAD

**Issue by Keno** [AsahiLinux/docs#4] opened 2021-07-02 23:27 UTC
The wiki page at https://github.com/AsahiLinux/docs/wiki/SW%3ALinux recommends building the main branch of https://github.com/AsahiLinux/linux and using it with the initrd from Debian and config-marcan. However, there appears to be some incompatibility here, as attempting to boot this configuration will yield:
```
Failed to create socket: Function not implemented
Failed to initialize udev control socket
Failed to create manager: Invalid argument
```
It would be nice if the steps outlined in the wiki gave a bootable Linux system for people to play around with.

**Comment by hablerentand** [comment] 2021-07-14 01:02
+1

**Comment by hablerentand** [comment] 2021-07-14 21:51
@amworsley do you know if this is an issue with the initrd and/or config-marcan linked in the SW:Linux guide?

**Comment by Keno** [comment] 2021-07-14 21:53
It's mostly the config. It's very minimal and doesn't have things like Unix domains sockets which debian requires.

**Comment by amworsley** [comment] 2021-07-14 23:45
Yep, it's the config file that is the problem. I have gotten a config based off one jannau gave me that I have tweaked a little to add CD (mount install CDs) and disabling address randomisation (allows stack tracing from System.map file) which I include below:

[config-jannau-iso9660-noR.gz](https://github.com/AsahiLinux/docs/files/6819425/config-jannau-iso9660-noR.gz)

You will need to rebuild your kernel with it.

I also use a modified initrd from Debian bullesys with the /init script starting a /bin/sh

I am able to get a USB keyboard (via a HUB) to enter characters

I still needed to start up udev (needed to create /dev files automatically when devices are plugged in) manually via:
   /lib/debian-installer/start-udev
But then I can mount USB keys/drives - I need a arm64 rootfs with more commands than
the initrd provides to do more though. It's a start.

Looking forward to when they get the native hardware set up fully via u-boot automatically - perhaps in a month or two?

**Comment by hablerentand** [comment] 2021-07-15 04:33
Thank you for attaching the new config file. I tried the it and it fixed the error reported by @Keno. However, I get a new error with the TTY later in the boot process. See command and output below:

**Command**:
```
proxyclient/tools/linux.py -b 'earlycon console=ttySAC0,1500000 console=tty0 debug' Image.gz build/dtb/t8103-j274.dtb initrd.gz
```

**End of the output**:
```
[...]
Ready to boot
DAIF: c0
TTY> pcie: initialized.
TTY> Preparing to boot kernel at 0x810a00000 with fdt at 0x80a3a8000
--- TTY mode | Quit: CTRL+] | Menu: CTRL+T ---
Preparing to run next stage at 0x810a00000...
Exception in thread rx:
Traceback (most recent call last):
--- Exit TTY mode ---
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/[...]/python3.9/site-packages/serial/tools/miniterm.py", line 499, in reader
    data = self.serial.read(self.serial.in_waiting or 1)
  File "/[...]/python3.9/site-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```

This is when following the instructions for "Running Linux via USB cable" > "Directly".

Do you know what may be the cause of this error?

**Comment by amworsley** [comment] 2021-07-15 04:57
Yep, when you start up the Linux it resets the USB and the USB serial service that was being supplied by m1n1 is lost as Linux overwrites m1n1 program!

Hence the python script on your host machine loses it's USB serial device...

You have two (not ideal) choices:
1. Plug in a USB keyboard *before* starting Asahi m1n1 so it can get the USB hardware up. I actually plug in a HUB with a keyboard in it - so I can plug in a USB drive later as well. You have to use the screen + USB keyboard to run commands.
2. Run the linux under the HV (hypervisor) via the run_guest.py script. Linux is run under the m1n1 program which can then keep the serial port open and working... But the serial port (known as vuart) is only a virtual hacky output only. i.e. You can't type things into it. Also unless you patch your linux, samsung serial driver FIFO size, it also locks up after printing out a line larger than 16 characters (the standard FIFO size) :-( But you can stop it, do stack traces et cetera. 

It's still a work in progress and you are reaching the (bleeding) cutting edge :-)

**Comment by hablerentand** [comment] 2021-07-19 17:18
Thank you for your reply @amworsley! I tried choice 1, but I wasn't able to get the USB keyboard to work.

I built the Asahi dart/dev kernel with the `config-jannau-iso9660-noR.gz` config file you attached. Then I used Apple's Type-C to Type-A adapter to plug in a normal old USB Dell keyboard to my **mac mini**'s second USB-C port. I verified that the keyboard works in 1TR, then booted Asahi m1n1, and finally booted Linux via the linux.py tool. Linux booted up until the language selection prompt, but the keyboard does not work so I was not able to get past such prompt. Is a different config file needed for a USB keyboard to work on a mac mini?

**Comment by hablerentand** [comment] 2021-07-21 21:12
Following up on the above, I modified the initrd to just run `/bin/sh`. When I boot the kernel compiled using `config-jannau-iso9660-noR.gz`, the boot process reaches `/bin/sh` successfully, but the keyboard input does not work (on my mac mini). When I boot the kernel compiled using the `[config-M1-dwc3](https://github.com/amworsley/asahi-wiki/blob/main/images/config-M1-dwc3)` linked in the guide (under the "Linux USB keyboard" section), the boot process ends with a kernel panic and yields:

```
Failed to create socket: Address family not supported by protocol
Failed to initialize udev control socket
Failed to create manager: Invalid argument
```

**Comment by amworsley** [comment] 2021-07-22 00:27
Hi hablerentand, config-M1-dwc3, is an even older config file than config-jannau-iso9660-noR.gz, so don't use it. I got the same problems you saw with it so I abandoned it
I've edited that reference in the Wiki to mention the newer and better one - so thanks for that fix.

I also noticed that the config-jannau-iso9660-noR.gz only supports "standard AT or PS/2 keyboard" via the KEYBOARD_ATKBD=y entry.
Most of the other keyboards are disabled,
```
% grep KEYBOARD  config-jannau-iso9660
CONFIG_INPUT_KEYBOARD=y
# CONFIG_KEYBOARD_ADP5588 is not set
# CONFIG_KEYBOARD_ADP5589 is not set
CONFIG_KEYBOARD_ATKBD=y
# CONFIG_KEYBOARD_QT1050 is not set
# CONFIG_KEYBOARD_QT1070 is not set
# CONFIG_KEYBOARD_QT2160 is not set
# CONFIG_KEYBOARD_DLINK_DIR685 is not set
# CONFIG_KEYBOARD_LKKBD is not set
# CONFIG_KEYBOARD_TCA6416 is not set
# CONFIG_KEYBOARD_TCA8418 is not set
# CONFIG_KEYBOARD_LM8333 is not set
# CONFIG_KEYBOARD_MAX7359 is not set
# CONFIG_KEYBOARD_MCS is not set
# CONFIG_KEYBOARD_MPR121 is not set
# CONFIG_KEYBOARD_NEWTON is not set
# CONFIG_KEYBOARD_OPENCORES is not set
# CONFIG_KEYBOARD_SAMSUNG is not set
# CONFIG_KEYBOARD_STOWAWAY is not set
# CONFIG_KEYBOARD_SUNKBD is not set
# CONFIG_KEYBOARD_OMAP4 is not set
# CONFIG_KEYBOARD_XTKBD is not set
# CONFIG_KEYBOARD_CAP11XX is not set
# CONFIG_KEYBOARD_BCM is not set
```
You can try editing the file by hand and re-compiling that kernel and see if that allows your keyboard to work. I don't know how to tell kind of keyboard you have, perhaps if you can insert it into another working Linux system the dmesg might give a useful message?

**Comment by hablerentand** [comment] 2021-07-22 15:49
Thanks for updating the guide @amworsley. I tried (separately) two old Dell USB keyboards very similar to the one of the photo in the guide. I edited the `config-jannau-iso9660-noR.gz` config file by hand, set all the `CONFIG_KEYBOARD_*` options to `y` and re-compiled and booted the kernel. Unfortunately the keyboard still does not work. Does keyboard input work with `config-jannau-iso9660-noR.gz` for you?

**Comment by amworsley** [comment] 2021-07-22 23:10
Yep it works fine with *my* old Dell keyboard - as shown in the photo!

Of course you have to have it all plugged in before you boot the iMAC as
there is some magic initialisation that the MacOS iBoot has to do to make USB work.

You might try asking sven on the IRC - #asahi as he is *the* expert on the USB on the M1

I've even gotten USB external drives and USB flash keys to work with that config.

Can you look at the dmesg log on your linux boot?
Check for anything with *USB* in it - it's probably a Mac Mini vs MacBook difference as
it sounds like your doing everything right.

**Comment by hablerentand** [comment] 2021-07-26 17:05
Thanks @amworsley for the reply. These are relevant dmesg logs from a linux desktop (is that what you meant?) booted with my old USB Dell keyboard attached. This keyboard is one of the two keyboards I tried (unsuccessfully) with Asahi on my mac mini.

```
[    1.287689] usb 1-8: New USB device found, idVendor=413c, idProduct=1003, bcdDevice= 1.00
[    1.287692] usb 1-8: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    1.287694] usb 1-8: Product: Dell USB Keyboard Hub
[    1.287695] usb 1-8: Manufacturer: Dell
[    1.288439] hub 1-8:1.0: USB hub found
[    1.570322] usb 1-8.1: new full-speed USB device number 3 using xhci_hcd
[    1.671158] usb 1-8.1: New USB device found, idVendor=413c, idProduct=2010, bcdDevice= 1.00
[    1.671162] usb 1-8.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    1.671164] usb 1-8.1: Product: Dell USB Keyboard Hub
[    1.671165] usb 1-8.1: Manufacturer: Dell
[    1.676354] usbcore: registered new interface driver usbhid
[    1.676361] usbhid: USB HID core driver
[    1.677909] input: Dell Dell USB Keyboard Hub as /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.1/1-8.1:1.0/0003:413C:2010.0001/input/input6
[    1.734431] hid-generic 0003:413C:2010.0001: input,hidraw0: USB HID v1.10 Keyboard [Dell Dell USB Keyboard Hub] on usb-0000:00:14.0-8.1/input0
[    1.734555] input: Dell Dell USB Keyboard Hub Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.1/1-8.1:1.1/0003:413C:2010.0002/input/input7
[    1.794360] input: Dell Dell USB Keyboard Hub System Control as /devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8.1/1-8.1:1.1/0003:413C:2010.0002/input/input8
[    1.794420] hid-generic 0003:413C:2010.0002: input,hidraw1: USB HID v1.10 Device [Dell Dell USB Keyboard Hub] on usb-0000:00:14.0-8.1/input1
```

Haven't seen sven online in the IRC - #asahi to ask him for help yet, but it seems that [someone else was able to get a USB keyboard to work on their mac mini](https://twitter.com/alyssarzg/status/1419469011734073347).

**Comment by amworsley** [comment] 2021-07-27 06:39
Your kernel is *definitely* seeing the Dell keyboard so that's not the problem.
I don't know but I will make a few, perhaps useless, comments:

1. I only have one input device found (input0) - you have input6, input8, input1 as well as input0. Could you be typing into the the non-zero inputs and the bash shell is only connected to input0 ?
2. I only get this working when booting directly to linux via the proxyclient/tools/linux.py script. Running under the HV it doesn't work *although* the Dell keyboard is detected in the Linux kernel messages. No input goes to the shell in this case - which sounds like what you have.
3.  Sven has made a new USB/dart version, which I haven't tried out yet. Perhaps worth trying and posting a photo of the console to the IRC and asking sven for help? He certainly knows more about this stuff than me - and he's very helpful - probably even more so if you are testing out his latest code....

**Comment by hablerentand** [comment] 2021-07-27 17:46
> Your kernel is definitely seeing the Dell keyboard so that's not the problem.

The `dmesg` logs I shared are from a separate Linux machine. I wasn't able to check dmesg on the mac mini itself since the keyboard does not work there. Is there a way to check dmesg on the mac mini without a working USB keyboard?

**Comment by amworsley** [comment] 2021-07-28 02:33
Doesn't the console display the kernel log?
I took a photo of my console and shared that.

If you are not seeing the console output on the screen - you are not going to be able to
do much as that is the only way to get output at the moment I believe.

**Comment by hablerentand** [comment] 2021-07-28 02:51
Here is a photo of what I see on the mac mini console: https://ibb.co/KbSgkjP

**Comment by amworsley** [comment] 2021-07-28 03:58
Hmm - Don't see the USB keyboard mentioned in that.

It says usbhid: USB HID core driver 

so you might think it would know about keyboard/mouse.

Did you try any other USB things and see if any of them are working?

You can try adding commands to the /init script on the initrd too

**Comment by hablerentand** [comment] 2021-07-28 17:22
Just ran more tests. I tried Alyssa's config file and also a new USB-C hub instead of my old adapter. Unfortunately, neither of those worked. However, I noticed that the status lights present in some of my adapters and USB keyboards do not turn on when booting into m1n1 nor when booting into Asahi Linux (which means they do not even get power?). Such status lights do turn on when booting in 1TR though. In one of your older messages you said that the keyboard needs to be plugged in before booting m1n1 "so it can get the USB hardware up". Is it possible that my issue is in the process of m1n1 "getting the USB hardware up"? I am using the m1n1 from the main branch and followed the instructions from here to install it: https://github.com/AsahiLinux/docs/wiki/Developer-Quickstart#using-m1n1

**Comment by amworsley** [comment] 2021-07-29 00:00
Getting the "USB hardware up" is probably two parts, correct me if you know more as
I am only vaguely across this.

Part 1. [USB-PD](https://github.com/AsahiLinux/docs/wiki/Glossary#u) (Power Delivery)  which I think is at a whole level in USB 3.0 / Type-C. The chips implementing it can provide lots of additional features. Some of which can be enabled by propriety protocols.
Booting the actual Mac with the device in will allow the early Mac firmware (iBoot1?) to configure these features.

Part 2. Normal USB standard features using public USB standard protocols. e.g. USB keyboards, mouse, ethernet, disks, WiFi ...

In particular high power states, charging et cetera needs the Part 1. stuff to be done on the MAC side. m1n1 doesn't do that stuff I think and Linux doesn't know how to do that on the M1 (yet?).

So plug in all your USB stuff *before* you even power on the Mac.
Hope that iBoot will happily set up the Mac hardware so only the part 2 stuff that Linux can do is needed.

I assume your keyboards work on the Mac when it is running the normal MacOS, lights on et cetera?

Have you tried editing the initrd ? e.g. extracting out the files, adding new commands to the /init shell script (echo "hello, world")? That might be your only way in unless you get
the serial port - USB Type-C set up that marcan has [Apple M1 Soc UART](https://lwn.net/Articles/845204/) which is built over the [USB-PD proprietry interface](https://github.com/AsahiLinux/docs/wiki/HW%3AUSB-PD#introductionl) which was reversed engineered

**Comment by hablerentand** [comment] 2021-07-29 23:00
Thanks so much for all your replies!

> Getting the "USB hardware up" is probably two parts, correct me if you know more as I am only vaguely across this.

That makes sense. I tried to unplug the keyboard and plug in my phone to the USB adapter after booting into Asahi. It charges. That suggests that Part 1 (Power Delivery) at least is working. I still haven't had any luck, however, with the keyboard. That means that Part 2 is not working.

> So plug in all your USB stuff before you even power on the Mac.

Yes, I have been testing with the adapter and keyboard attached before even powering on the Mac.

> I assume your keyboards work on the Mac when it is running the normal MacOS, lights on et cetera?

Yes, the keyboards work on the Mac when it is running the normal MacOS. They also work in 1TR before booting up m1n1.

> Have you tried editing the initrd ?

Yes, I tried editing the initrd following your old instructions from [here](https://github.com/amworsley/asahi-wiki/blob/main/SW:Linux.md). So far, I only changed the `init=` line from `init='/bin/busybox init'` to `init='/bin/sh'`. Does that sound right?

---

A subtle detail not mentioned in your guide is that when running `make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- oldconfig` (after `cp config-jannau-iso9660-noR .config`), I get multiple prompts asking about additional configuration options (e.g., `Use pointer authentication for kernel (ARM64_PTR_AUTH_KERNEL) [Y/n/?] (NEW)`). In my tests I left those configuration options all to their default values by pressing Enter. Is this okay/expected?  

One more small detail. I have been booting the kernels with the command `python3 proxyclient/tools/linux.py -b 'earlycon console=ttySAC0,1500000 console=tty0 debug' Image.gz ./build/dtb/t8103-j274.dtb init-new.gz`. Does this command sound right?

**Comment by amworsley** [comment] 2021-07-29 23:41
Not a problem answering your enquires - very keen to see you make progress as it helps me learn more.

Power delivery has several levels - so does you phone do fast charging? Normal old USB-2 doesn't do that - so just "charging" can be just the basic level, presumably USB-2 feature.

That said, I saw Sven's comment on the IRC about USB-3 not working and using a dumb USB-2 adapter.

I just used this [USB 3.1 Type C Male to USB 3.0 A Female Converter USB-C Cable Adapter OTG](https://www.ebay.com/itm/173782187555))
and I think it was this [Simplecom USB Type-C to TypeA HUB](https://cplonline.com.au/simplecom-ch320-usb-type-c-to-4-port-usb-3-0-hub-for-pc-mac-laptop.html)

You might try removing  the "console=ttySAC0,1500000" as you loose that fake samsung serial port when the m1n1 USB fake serial interface goes away when linux is started.

You definitely want the console=tty0 to get the console messages on the screen/framebuffer. The earlycon get's you a console from very early in the Linux boot (before normal printk()s are up). I think debug get's you extra printk()s.

The actual .dtb (device tree binary) file I used came from Sven's kernel linux/arch/arm64/boot/dts/apple - not the m1n1 - but I suspect it doesn't make a difference unless you
are trying to disable the first USB port so you can run the kernel under the HV which uses a USB port for communications. Your not, you using linux.py - directly running the kernel.

It would be great if it was just the console=ttySAC0 was the problem. Anyway  just on the
chance perhaps you can discern some little but critical difference
my actual text notes I have are :
```
cp config-jannau-full ../linux
cd ../linux
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j8 Image

* NOTE: Make sure CONFIG_RANDOMIZE_BASE is OFF otherwise backtrace won't work!

* In m1n1
gzip < ../linux/arch/arm64/boot/Image > Image-marcan-dart-noR.gz

* Make sure environment variable is set for the USB tty
M1N1DEVICE=/dev/ttyACM0
export M1N1DEVICE

* initrd-be2.gz - patched debian bullseye initrd?
* t8103-j274.dtb - kernel apple M1 device tree (no USB disabled)
* m1n1 - 9f0bc3f make -> chain load
python3.9 proxyclient/tools/chainload.py build/m1n1.macho

* Boots up with /bin/sh in initrd after 10 printk messages
python3.9 proxyclient/tools/linux.py -b 'earlycon console=tty0  console=tty0 debug' Image-marcan-dart-dev.gz t8103-j274.dtb initrd-be2.gz


 * Create .macho to run under HV
* appleM1-No-dwc0.dtb - kernel apple M1 with USB disabled to allow fake vuart via USB port
* Image-marcan-dart-dev-9660.gz - jannau config + ISO9660 CDRom support kernel
cat build/m1n1.macho Image-marcan-dart-noR.gz  appleM1-No-dwc0.dtb initrd-be2.gz > m1n1-payload-dart-noR.macho

* Load image under HV
python3.9 proxyclient/tools/run_guest.py -S m1n1-payload-dart-noR.macho

^CUser interrupt
Entering hypervisor shell
>>> load_system_map('../linux/System.map')
>>> hv.pac_mask = 0xffff800000000000
>>> bt
Stack trace:
 - 0xffff8000108a8ecc (cpu_do_idle+0xc)
 - 0xffff8000108a8eec (arch_cpu_idle+0xc)
 - 0xffff8000108b20e0 (default_idle_call+0x20)
 - 0xffff8000100b2180 (do_idle+0x208)
 - 0xffff8000100b23f4 (cpu_startup_entry+0x24)
 - 0xffff8000108a973c (rest_init+0xd4)
 - 0xffff800010bf0b9c (arch_call_rest_init+0xc)
 - 0xffff800010bf10e8 (start_kernel+0x500)
```

My /init script in my modified initrd from debian bullseye is:
```
#!/bin/sh
# used for initramfs
echo "M1 Linux #usb2"
export PATH

/bin/mount /run
/bin/mkdir -p /run/lock
/bin/mount /proc
/bin/mount /sys

echo "Starting Shell"
I=1
while [ "$I" -le 10 ]; do
        echo "Still running $I"
        sleep 1
        I=$(($I+1))
done

/bin/sh
````

If you can get these "Still running " messages on the console - then you could put some
other stuff to probe the USB? Or at least debug things was my thinking.

**Comment by hablerentand** [comment] 2021-07-30 02:53
Thanks very much! Your message helped me finally figure out what the issue was! The issue was that I was using the wrong `t8103-j274.dtb` (device tree binary) file. Using the dtb from the `linux/arch/arm64/boot/dts/apple` folder (rather than the m1n1 one) fixed the keyboard issues! I really appreciate your help figuring this out!

**Comment by amworsley** [comment] 2021-07-30 05:11
Fantastic!  - Sven's dtsi file  has a lot of extra USB (dwc3) stuff so that will be exactly
why you needed the new one.

I'm going to add a foot note to the Wiki to help others from your experience!

**Comment by marcan** [comment] 2022-03-15 04:19
This is very out of date, closing.

**Closed by marcan** 2022-03-15 04:19 UTC
